name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vinayswamy/rstudio-example:latest
    - name: push to Dockerhub
      run: docker push vinayswamy/rstudio-example:latest
